const ROOM_NAMES={scientist:'科研室',entrepreneur:'商业室',creator:'创作室',human:'生活室'};
const XP={easy:5,normal:10,hard:20};
const DIFFICULTY={easy:'轻松',normal:'普通',hard:'困难'};
const TODAY=new Date().toISOString().slice(0,10);
const STORAGE_KEY='yuxin-life-lab-v1';
const defaultState={xp:0,tasks:[],projects:[],notes:[],journals:[],reviews:[],room:'scientist'};
let state=loadLocal();let supabase=null;let user=null;

const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
function loadLocal(){try{return {...defaultState,...JSON.parse(localStorage.getItem(STORAGE_KEY)||'{}')}}catch{return structuredClone(defaultState)}}
function saveLocal(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state))}
function uid(){return crypto.randomUUID()}
function escapeHtml(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function weekStart(date=new Date()){const d=new Date(date);const day=(d.getDay()+6)%7;d.setDate(d.getDate()-day);d.setHours(0,0,0,0);return d}
function dateString(d){return d.toISOString().slice(0,10)}
function inCurrentWeek(s){const d=new Date(s+'T12:00:00'),start=weekStart(),end=new Date(start);end.setDate(end.getDate()+7);return d>=start&&d<end}

async function initCloud(){const cfg=window.LIFE_LAB_CONFIG||{};if(!cfg.supabaseUrl||cfg.supabaseUrl.startsWith('YOUR_')||!cfg.supabasePublishableKey||cfg.supabasePublishableKey.startsWith('YOUR_')){renderAll();return}try{const {createClient}=await import('https://esm.sh/@supabase/supabase-js@2');supabase=createClient(cfg.supabaseUrl,cfg.supabasePublishableKey);const {data}=await supabase.auth.getSession();user=data.session?.user||null;supabase.auth.onAuthStateChange((_e,s)=>{user=s?.user||null;if(user)syncFromCloud();else renderAll()});if(user)await syncFromCloud();else renderAll()}catch(e){$('#auth-notice').textContent='云端连接暂不可用，已保留本机数据。';renderAll()}}
async function syncFromCloud(){if(!supabase||!user)return;const queries=await Promise.all(['tasks','projects','room_notes','journals','weekly_reviews','xp_events'].map(t=>supabase.from(t).select('*')));if(queries.some(x=>x.error)){showNotice('同步时遇到问题，本机数据仍安全保存。');return}state.tasks=queries[0].data||[];state.projects=queries[1].data||[];state.notes=queries[2].data||[];state.journals=queries[3].data||[];state.reviews=queries[4].data||[];state.xp=(queries[5].data||[]).reduce((s,x)=>s+x.amount,0);saveLocal();renderAll()}
async function cloudUpsert(table,row){if(!supabase||!user)return;const payload={...row,user_id:user.id};const {error}=await supabase.from(table).upsert(payload);if(error)showNotice('云端保存失败，已先保存在本机。')}
async function cloudDelete(table,id){if(supabase&&user)await supabase.from(table).delete().eq('id',id)}
function showNotice(msg){$('#greeting').textContent=msg;setTimeout(()=>$('#greeting').textContent='欢迎回来，老大',3500)}

function renderAll(){saveLocal();$('#xp').textContent=Math.max(0,state.xp);$('#sync-state').textContent=user?'云端已同步':'本机体验模式';const todays=state.tasks.filter(t=>t.task_date===TODAY);$('#today-count').textContent=`${todays.filter(t=>t.completed_at).length} / ${todays.length}`;$('#streak').textContent=journalStreak();renderTasks();renderCalendar();renderRoom();renderReview();renderJournal();}
function journalStreak(){let n=0,d=new Date();const dates=new Set(state.journals.map(j=>j.journal_date));while(dates.has(dateString(d))){n++;d.setDate(d.getDate()-1)}return n}
function taskRow(t){return `<div class="task"><input type="checkbox" data-complete="${t.id}" ${t.completed_at?'checked':''} aria-label="完成任务"><span>${escapeHtml(t.title)} ${t.is_must?'<em class="must">· 必须</em>':''}<small>${ROOM_NAMES[t.room]} · ${DIFFICULTY[t.difficulty]} · ${t.completed_at?'+':''}${t.xp_reward||XP[t.difficulty]} XP · ${t.task_date}${t.task_time?' '+t.task_time.slice(0,5):''}</small></span><button class="danger" data-delete-task="${t.id}">删除</button></div>`}
function renderTasks(){const fixed=state.tasks.filter(t=>t.task_type==='fixed'&&t.task_date===TODAY),temp=state.tasks.filter(t=>t.task_type==='temporary'&&t.task_date===TODAY);$('#fixed-tasks').innerHTML=fixed.map(taskRow).join('')||'<p class="empty">今天还没有固定任务。</p>';$('#temporary-tasks').innerHTML=temp.map(taskRow).join('')||'<p class="empty">今天还没有临时任务。</p>';$$('[data-complete]').forEach(x=>x.onchange=()=>toggleTask(x.dataset.complete,x.checked));$$('[data-delete-task]').forEach(x=>x.onclick=()=>deleteTask(x.dataset.deleteTask))}
async function toggleTask(id,done){const t=state.tasks.find(x=>x.id===id);if(!t)return;const amount=t.xp_reward||XP[t.difficulty];t.completed_at=done?new Date().toISOString():null;state.xp=Math.max(0,state.xp+(done?amount:-amount));saveLocal();if(user){await cloudUpsert('tasks',t);await cloudUpsert('xp_events',{id:uid(),task_id:t.id,amount:done?amount:-amount,reason:done?'task_completed':'task_uncompleted',event_date:TODAY})}renderAll()}
async function deleteTask(id){state.tasks=state.tasks.filter(t=>t.id!==id);saveLocal();await cloudDelete('tasks',id);renderAll()}

function renderCalendar(){const start=weekStart();const names=['周一','周二','周三','周四','周五','周六','周日'];$('#week').innerHTML=names.map((n,i)=>{const d=new Date(start);d.setDate(d.getDate()+i);const ds=dateString(d);const items=state.tasks.filter(t=>t.task_date===ds).sort((a,b)=>(a.task_time||'99').localeCompare(b.task_time||'99')).map(t=>`<span class="chip ${t.is_must?'must':''}">${t.task_time?t.task_time.slice(0,5):'自由'} · ${escapeHtml(t.title)}${t.completed_at?' ✓':''}</span>`).join('');return `<article class="day"><strong>${n} ${d.getMonth()+1}/${d.getDate()}</strong>${items||'<span class="empty">留白</span>'}</article>`}).join('')}

function renderRoom(){const room=state.room;$('#room-title').textContent=ROOM_NAMES[room];$('#room-select').value=room;const projects=state.projects.filter(p=>p.room===room);$('#projects').innerHTML=projects.map(p=>`<div class="record"><strong>${escapeHtml(p.title)}</strong><small>${escapeHtml(p.goal||'')} · ${p.stage} ${p.due_date?'· '+p.due_date:''}</small><div class="progress"><i style="width:${p.progress||0}%"></i></div><button class="danger" data-delete-project="${p.id}">删除</button></div>`).join('')||'<p class="empty">还没有项目。</p>';const notes=state.notes.filter(n=>n.room===room).sort((a,b)=>b.record_date.localeCompare(a.record_date));$('#room-notes').innerHTML=notes.map(n=>`<div class="record">${escapeHtml(n.content)}<small>${n.record_date}</small><button class="danger" data-delete-note="${n.id}">删除</button></div>`).join('')||'<p class="empty">还没有记录。</p>';$$('[data-delete-project]').forEach(b=>b.onclick=()=>removeItem('projects',b.dataset.deleteProject));$$('[data-delete-note]').forEach(b=>b.onclick=()=>removeItem('notes',b.dataset.deleteNote,'room_notes'))}
async function removeItem(key,id,table=key){state[key]=state[key].filter(x=>x.id!==id);saveLocal();await cloudDelete(table,id);renderAll()}

function renderJournal(){const j=state.journals.find(x=>x.journal_date===TODAY);if(!j)return;for(const name of ['event_text','feelings','body_state','self_credit','needs','free_text'])$('#journal-form').elements[name].value=j[name]||''}
function renderReview(){const tasks=state.tasks.filter(t=>inCurrentWeek(t.task_date));const done=tasks.filter(t=>t.completed_at);const notes=state.notes.filter(n=>inCurrentWeek(n.record_date));const journals=state.journals.filter(j=>inCurrentWeek(j.journal_date));const mustOpen=tasks.filter(t=>t.is_must&&!t.completed_at);$('#review-summary').innerHTML=`<li>完成 ${done.length}/${tasks.length} 项任务。</li><li>本周获得 ${done.reduce((s,t)=>s+(t.xp_reward||XP[t.difficulty]),0)} XP。</li><li>四个房间新增 ${notes.length} 条记录。</li><li>写下 ${journals.length} 篇日记。</li><li>${mustOpen.length?`有 ${mustOpen.length} 项必须任务需要延期、调整或放下。`:'所有必须任务都完成了。'}</li>`}

$$('#nav button').forEach(b=>b.onclick=()=>showPage(b.dataset.page));function showPage(name){$$('.page').forEach(p=>p.classList.toggle('active',p.id===`page-${name}`));$$('#nav button').forEach(b=>b.classList.toggle('active',b.dataset.page===name));if(name==='review')renderReview()}
$$('[data-room]').forEach(b=>b.onclick=()=>{state.room=b.dataset.room;showPage('rooms');renderRoom()});$('#room-select').onchange=e=>{state.room=e.target.value;renderRoom();saveLocal()};
$$('[data-add-type]').forEach(b=>b.onclick=()=>{const f=$('#task-form');f.reset();f.elements.task_type.value=b.dataset.addType;f.elements.task_date.value=TODAY;$('#task-dialog').showModal()});
$('#task-form').addEventListener('submit',async e=>{e.preventDefault();if(e.submitter?.value!=='save'){e.target.closest('dialog').close();return}const f=new FormData(e.target),difficulty=f.get('difficulty');const task={id:uid(),title:f.get('title').trim(),room:f.get('room'),task_type:f.get('task_type'),difficulty,xp_reward:XP[difficulty],is_must:f.get('is_must')==='on',task_date:f.get('task_date'),task_time:f.get('task_time')||null,completed_at:null};state.tasks.push(task);saveLocal();await cloudUpsert('tasks',task);$('#task-dialog').close();renderAll()});
$('#add-project').onclick=()=>{$('#project-form').reset();$('#progress-value').textContent='0%';$('#project-dialog').showModal()};$('#project-form').elements.progress.oninput=e=>$('#progress-value').textContent=e.target.value+'%';$('#project-form').addEventListener('submit',async e=>{e.preventDefault();if(e.submitter?.value!=='save'){e.target.closest('dialog').close();return}const f=new FormData(e.target);const p={id:uid(),room:state.room,title:f.get('title').trim(),goal:f.get('goal'),stage:f.get('stage'),progress:Number(f.get('progress')),due_date:f.get('due_date')||null};state.projects.push(p);saveLocal();await cloudUpsert('projects',p);$('#project-dialog').close();renderAll()});
$('#note-form').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);const n={id:uid(),room:state.room,content:f.get('content').trim(),record_date:TODAY,project_id:null};state.notes.unshift(n);saveLocal();await cloudUpsert('room_notes',n);e.target.reset();renderAll()};
$('#journal-form').onsubmit=async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.target));let j=state.journals.find(x=>x.journal_date===TODAY);if(j)Object.assign(j,data);else{j={id:uid(),journal_date:TODAY,...data};state.journals.push(j)}saveLocal();await cloudUpsert('journals',j);$('#journal-notice').textContent='已保存，老大。今天的你被好好记录下来了。';renderAll()};
$('#copy-ai').onclick=async()=>{const f=$('#journal-form').elements;const prompt=`请温柔、清晰地整理我的情绪记录。忠于事实，不诊断、不说教，先帮我识别感受与需要，再给一个很小的下一步。\n\n发生的事：${f.event_text.value}\n感受：${f.feelings.value}\n身体：${f.body_state.value}\n值得肯定：${f.self_credit.value}\n需要：${f.needs.value}\n补充：${f.free_text.value}`;await navigator.clipboard.writeText(prompt);$('#journal-notice').textContent='已复制。可以粘贴到免费的 ChatGPT 或 DeepSeek。'};
$('#save-review').onclick=async()=>{const start=dateString(weekStart()),end=new Date(weekStart());end.setDate(end.getDate()+6);const r={id:uid(),week_start:start,week_end:dateString(end),reflection:$('#reflection').value,next_week_top_three:$('#top-three').value.split('\n').filter(Boolean),generated_summary:{task_count:state.tasks.filter(t=>inCurrentWeek(t.task_date)).length},confirmed_at:new Date().toISOString()};state.reviews.push(r);saveLocal();await cloudUpsert('weekly_reviews',r);$('#review-notice').textContent='已存入档案。老大，下一周继续稳稳向前。'};
$('#login').onclick=async()=>{if(!supabase){$('#auth-notice').textContent='请先在 config.js 中填写 Supabase 公开配置。';return}const email=$('#email').value.trim();if(!email){$('#auth-notice').textContent='请填写邮箱。';return}const {error}=await supabase.auth.signInWithOtp({email,options:{emailRedirectTo:location.href}});$('#auth-notice').textContent=error?error.message:'登录链接已发送，请检查邮箱。'};$('#logout').onclick=async()=>{if(supabase)await supabase.auth.signOut();user=null;renderAll()};

initCloud();
